version: '3'

services:
  
  db:
    image: postgres:14.3
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
      - .prod.env

  bot:
    depends_on:
      - db
    image: home-storage/bot
    volumes:
      - ${DB_IMAGE_PATH}:/usr/src/app/${DB_IMAGE_PATH}
    env_file:
      - .env
      - .prod.env

    command: bash -c "npm run typeorm migration:run && npm start"



