version: '3'

services:
  
  db:
    image: postgres:14.3
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  bot:
    depends_on:
      - db
    image: home-storage/bot
    command: npm start


